apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-rc 
  labels:
    app: myapp
    type: Front-end
spec:
  template: 
    
    metadata: 
      name: myapp-pod
      labels: 
        app: myapp-pod
        type: Back-end
    spec:
      containers: 
      -  name: nginx-container
         image: nginx
  replicas: 2

#Commands
#kubectl create -f create-rc.yaml
#kubectl get replicationcontroller
#kubectl delete -f create-replicaset.yaml or kubectl delete replicaset myapp-rc  
