apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ${OBJECT_NAME}
  labels:
    app: ${APP_NAME}
    ref: ${IDENTIFIER}
spec:
  revisionHistoryLimit: 10
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: '${OBJECT_NAME}:${IDENTIFIER}'
  replicas: 1
  test: false
  selector:
    app: ${APP_NAME}
    ref: ${IDENTIFIER}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${APP_NAME}
        ref: ${IDENTIFIER}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ${APP_NAME}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: ${APP_NAME}
          image: >-
            ahtaaja.saunalahti.fi/${ORG_NAME}/${APP_NAME}/${APP_NAME}:${IDENTIFIER}
          ports:
            - containerPort: ${PORT}
              protocol: TCP
          resources:
            limits:
              cpu: '500m'
              memory: 512Mi
            requests:
              cpu: '200m'
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: '${READINESS_PROBE_PATH}'
              port: ${READINESS_PROBE_PORT}
              scheme: '${READINESS_PROBE_SCHEME}'
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: '${READINESS_PROBE_PATH}'
              port: ${READINESS_PROBE_PORT}
              scheme: '${READINESS_PROBE_SCHEME}'
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: ahtaaja
