kind: Template
apiVersion: v1
metadata:
  name: jpd-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: johnb-test
  spec:
    replicas: 1
    selector:
      app: gsm-billing-changes-test
      deploymentconfig: gsm-billing-changes-test
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: gsm-billing-changes-test
          deploymentconfig: gsm-billing-changes-test
      spec:
        containers:
          - image: >-
              ahtaaja.saunalahti.fi/jpd/devel/public/gsm-billing-changes/lltdeploy:latest
            imagePullPolicy: Always
            name: gsm-billing-changes-test
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        envFrom:
        - name: ${CONFIG_MAP_NAME}
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - ${APP_NAME}
          from:
            kind: ImageStreamTag
            name: "${APP_NAME}:latest"
      - type: ImageChange
parameters:
- APP_NAME: gsm-billing-changes-test
  required: true
  description: application name
- CONFIG_MAP_NAME: gsm-billing-changes-test
  required: true
