apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: mappo-test
  name: mappo-test
spec:
  replicas: 1
  selector:
    app: mappo-test
    deploymentconfig: mappo-test
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  template:
    metadata:
      labels:
        app: mappo-test
        deploymentconfig: mappo-test
    spec:
      containers:
        - image: >-
            ahtaaja.saunalahti.fi/jpd/devel/public/mappo/lltdeploy
          imagePullPolicy: Always
          name: mappo-test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mappo-test
        from:
          kind: ImageStreamTag
          name: 'mappo:latest'
      type: ImageChange
